---
- name: playbook to write motd to all servers in inventory file
  hosts: all
  tasks:
    - name: copy custom motd msg to managed nodes using group_vars
      copy:
        content: "{{ motd_msg }}"
        dest: /etc/motd
...
