---
- name: playbook to install custom packages
  hosts: all
  become: yes
  vars:
    proxy_packages:
      - tcpdump
      - mailx
    database_packages:
      - lsof
      - mailx
  tasks:
    - name: install packages for proxy
      yum:
        name: "{{ proxy_packages }}"
        state: present
      when: inventory_hostname in groups["proxy"]

    - name: install packages for database
      yum:
        name: "{{ database_packages }}"
        state: present
      when: inventory_hostname in groups["database"]
...
