---
- name: playbook to setup a yum repo 
  hosts: "database"
  become: yes
  tasks:
    - name: setup repo
      yum_repository:
        name: "mysql80-community"
        description: "MySQL 8.0 YUM Repo"
        baseurl: "http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/"
        gpgkey: "http://repo.mysql.com/RPM-GPG-KEY-mysql"
        state: present
        gpgcheck: yes
        enabled: yes
...
