---
- name: playbook to create a server list on target machine
  hosts: all
  become: yes
  tasks:
    - name: use template to create server list on target machine/s
      template:
        src: ./templates/server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        group: automation
        mode: "0600"
        setype: net_conf_t
      when: inventory_hostname in groups["database"]
...
