---
- name: playbook to modify sshd configuration
  hosts: all
  tasks:
    - name: set banner to /etc/motd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#Banner"
        line: "Banner /etc/motd"
        state: present
        backup: yes
    
    - name: disable X11 forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^X11Forwarding"
        line: "X11Forwarding no"
        state: present

    - name: modify auth tries
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#MaxAuthTries"
        line: "MaxAuthTries 3"
        state: present
      notify: restart_ssh
  
  handlers:
    - name: restart_ssh
      service:
        name: sshd
        state: restarted
...
