---
- name: playbook to convert int to string and index the string
  hosts: ansible2
  vars:
    - my_num: 1234
  tasks:
    - name: display the first char of my num
      debug:
        msg: "first char is {{ my_num | string | first }}"

    - name: convert my_num to a string and store it in a variable
      set_fact:
        my_str: "{{ my_num | string }}"
      
    - name: print string
      debug:
        msg: "second char is {{ my_str[1] }}"
...
