---
- name: playbook for conditional control
  hosts: all
  tasks:
    - name: set vm.swappiness variable if ram is >= 2048 MB
      sysctl: 
        name: vm.swappiness
        value: 25
      when: ansible_facts['memfree_mb'] >= 2048
    
    - name: display error if ram is less than 2048 MB
      fail:
        msg: Server memory less than 2048MB
      when: ansible_facts['memfree_mb'] < 2048
...


