---
- name: playbook to create users, set passwords, and provide ssh keys
  hosts: all
  vars_files:
    - user_list.yaml
    - secret.yaml
  become: yes
  tasks:
    - name: create users with ID starting with "1"
      include_tasks: create_user.yaml 
      loop: "{{ users }}"
      when: inventory_hostname in groups["webservers"] and item.uid | string | first == "1"

    - name: create users with ID starting with "2"
      include_tasks: create_user.yaml
      loop: "{{ users }}"
      when: inventory_hostname in groups["database"] and item.uid | string | first == "2"
...
