---
# tasks file for sample-apache
- name: install httpd, mod_ssl, and php
  yum:
    name:
      - httpd
      - mod_ssl
      - php
    state: present

- name: start and enable apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: firewalld configuration http
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - http
    - https

  
- name: create index.html content with template
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify: restart_httpd
...    
