---
# tasks to create partition, vg, and lvol and mount the lvol
- name: create partition on /dev/sdb
  parted:
    device: /dev/sdb
    flags: lvm
    number: 1
    part_end: 800MB
    fs_type: xfs
    state: present

- name: create volume group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1
    
- name: create logical volume
  lvol:
    lv: lv_mysql
    vg: vg_database
    size: 512M

- name: create filesystem on lv
  filesystem:
    dev: /dev/vg_database/lv_mysql
    fstype: xfs

- name: permanently mount lv
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted #mounting point will be create if it does not exist
...
